---
name: ci
on: pull_request
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: .ci/yamllint.yml
          strict: true

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35.0

  excludeFmtErrorf:
    name: exclude fmt.Errorf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Exclude fmt.Errorf
        run: |
          if grep -r --include=*.go --exclude=*.pb.go fmt.Errorf . ; then
           echo "Please use errors.Errorf (or errors.New or errors.Wrap or errors.Wrapf) as appropriate rather than fmt.Errorf"
           exit 1
          fi

  checkgomod:
    name: check go.mod and go.sum
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - run: go mod tidy
      - name: Check for changes in go.mod or go.sum
        run: |
          git diff --name-only --exit-code go.mod || ( echo "Run go tidy" && false )
          git diff --name-only --exit-code go.sum || ( echo "Run go tidy" && false )

  automerge:
    name: automerge
    runs-on: ubuntu-latest
    needs:
      - packet
    if: github.actor == 'nsmbot' && github.base_ref == 'master' && github.event_name == 'pull_request'
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch master
        run: |
          git remote -v
          git fetch --depth=1 origin master
      - name: Only allow go.mod and go.sum changes
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' -exec git diff --exit-code origin/master -- {} +
      - name: Automerge nsmbot PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: nsmbot
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packet:
    name: packet
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl                     # 1. Set up kubectl
        uses: azure/setup-kubectl@v1
      - name: Set up /bin permissions            # 2. Set up /bin permissions
        run: |
          sudo chmod -R 777 /bin
      - name: Set up go                          # 3. Set up go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Install go tools                   # 4. Install go tools
        run: |
          go get github.com/networkservicemesh/gotestmd@main
          go get golang.org/x/tools/cmd/goimports
          go get github.com/networkservicemesh/cloudtest@master
        env:
          GO111MODULE: on
          GOBIN: /bin
      - name: Checkout deployments               # 5. Checkout deployments
        uses: actions/checkout@v2
        with:
          repository: Bolodya1997/deployments-k8s
          ref: sriov
          path: Bolodya1997/deployments-k8s
      - name: Checkout files                     # 6. Checkout files
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - name: Check generated tests              # 7. Check generated tests
        working-directory: ${{ github.repository }}
        run: |
          go generate ./...
          git diff --name-only --exit-code || ( echo "Run go generate" && false )
      - name: Run tests with cloudtest           # 8. Run tests with cloudtest
        working-directory: ${{ github.repository }}
        run: |
          cloudtest
        env:
          PACKET_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
          PACKET_PROJECT_ID: 383890d0-f5d1-4de1-881a-4d1ede549d18
      - name: (on error) Upload logs             # 9. (on error) Upload logs
        uses: actions/upload-artifact@v2
        if: ${{ failure() || cancelled() }}
        with:
          name: logs-${{ github.run_number }}
          path: ${{ github.repository }}/.tests/cloud_test/

  packet-cleanup:
    runs-on: ubuntu-latest
    needs:
      - packet
    if: ${{ always() }}
    steps:
      - name: Set up /bin permissions
        run: |
          sudo chmod -R 777 /bin
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Clean up packet
        run: |
          go get github.com/networkservicemesh/cloudtest/pkg/providers/packet/packet_cleanup@master
          packet_cleanup
        env:
          GO111MODULE: on
          GOBIN: /bin
          PACKET_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
          PACKET_PROJECT_ID: 383890d0-f5d1-4de1-881a-4d1ede549d18
